//! Signal Reader - Reads trading signals from Redis.
//!
//! This module is responsible for reading trading signals generated by Muscle-Kit
//! from Redis and converting them to a format suitable for LLM consumption.

use anyhow::{Context, Result};
use redis::Client;
use tracing::debug;
use zeroclaw_common::{SignalOutput, MarketRegime, Signal};

/// Signal Reader that reads from Redis `market:signal:{SYMBOL}`
pub struct SignalReader {
    redis: Client,
    key_prefix: String,
}

impl SignalReader {
    /// Create a new Signal Reader
    pub fn new(redis: Client, key_prefix: Option<&str>) -> Self {
        Self {
            redis,
            key_prefix: key_prefix.unwrap_or("market:signal").to_string(),
        }
    }

    /// Get the Redis key for a symbol's signal
    fn get_signal_key(&self, symbol: &str) -> String {
        format!("{}:{}", self.key_prefix, symbol.to_uppercase())
    }

    /// Read signal for a symbol from Redis
    pub fn read_signal(&self, symbol: &str) -> Result<Option<SignalOutput>> {
        let key = self.get_signal_key(symbol);
        let mut conn = self.redis.get_connection().context("Failed to get Redis connection")?;
        
        let json: Option<String> = redis::cmd("GET")
            .arg(&key)
            .query(&mut conn)
            .context("Failed to read signal from Redis")?;

        match json {
            Some(json_str) => {
                let signal: SignalOutput = serde_json::from_str(&json_str)
                    .context("Failed to deserialize SignalOutput")?;
                debug!("Read signal for {}: {:?}", symbol, signal.market_regime);
                Ok(Some(signal))
            }
            None => {
                debug!("No signal found for {}", symbol);
                Ok(None)
            }
        }
    }

    /// Read signals for multiple symbols
    pub fn read_signals_batch(&self, symbols: &[&str]) -> Result<Vec<SignalOutput>> {
        let mut signals = Vec::new();
        let mut conn = self.redis.get_connection().context("Failed to get Redis connection")?;
        
        for &symbol in symbols {
            let key = self.get_signal_key(symbol);
            let json: Option<String> = redis::cmd("GET")
                .arg(&key)
                .query(&mut conn)
                .ok()
                .flatten();
            
            if let Some(json_str) = json {
                if let Ok(signal) = serde_json::from_str::<SignalOutput>(&json_str) {
                    signals.push(signal);
                }
            }
        }

        Ok(signals)
    }

    /// Check if signal is reliable based on latency
    pub fn is_signal_reliable(signal: &SignalOutput, max_latency_ms: i64) -> bool {
        signal.ingestion_latency_ms <= max_latency_ms
            && signal.override_reason.as_deref() != Some("LATENCY_SPIKE")
    }

    /// Convert signal to human-readable format for LLM prompt
    pub fn signal_to_prompt(&self, signal: &SignalOutput) -> String {
        let snapshot = &signal.indicator_snapshot;
        
        format!(
            r#"**Current Price**: ${price}
**Market Regime**: {regime}
**Confluence Score**: {score}/10

**Technical Indicators**:
- RSI (14): {rsi}
- MACD: {macd} (Signal: {macd_signal}, Histogram: {macd_histogram})
- ADX: {adx}
- Bollinger Band Width: {bb_width}
- ATR: {atr}
- Ultimate Smoother: {us_value}
- BB Upper: {bb_upper}
- BB Lower: {bb_lower}

**Muscle-Kit Advice**: {advice}

**Signal Metadata**:
- Timestamp: {timestamp}
- Ingestion Latency: {latency}ms
- Override Reason: {override}"#,
            price = signal.price,
            regime = signal.market_regime,
            score = signal.confluence_score,
            rsi = snapshot.rsi,
            macd = snapshot.macd,
            macd_signal = snapshot.macd_signal,
            macd_histogram = snapshot.macd_histogram,
            adx = snapshot.adx,
            bb_width = snapshot.bb_width,
            atr = snapshot.atr,
            us_value = snapshot.us_value,
            bb_upper = snapshot.bb_upper,
            bb_lower = snapshot.bb_lower,
            advice = signal.action(),
            timestamp = signal.timestamp_ms,
            latency = signal.ingestion_latency_ms,
            override = signal.override_reason.as_deref().unwrap_or("None"),
        )
    }

    /// Get market regime description
    pub fn regime_description(regime: &MarketRegime) -> &'static str {
        match regime {
            MarketRegime::Trending => "Strong trend market (ADX > 25) - Suitable for trend following strategies",
            MarketRegime::Ranging => "Range-bound market (ADX < 20) - Suitable for mean reversion strategies",
            MarketRegime::Volatile => "High volatility market - Use caution, consider reducing position size",
        }
    }

    /// Get signal description
    pub fn signal_description(signal: &Signal) -> &'static str {
        match signal {
            Signal::Long { strength } => match strength {
                s if *s >= 0.8 => "Strong LONG signal",
                s if *s >= 0.5 => "Moderate LONG signal",
                _ => "Weak LONG signal",
            },
            Signal::Short { strength } => match strength {
                s if *s >= 0.8 => "Strong SHORT signal",
                s if *s >= 0.5 => "Moderate SHORT signal",
                _ => "Weak SHORT signal",
            },
            Signal::Wait => "WAIT - No clear direction, stay out of market",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_get_signal_key() {
        let reader = SignalReader::new(
            ConnectionManager::ignore(),
            Some("market:signal"),
        );
        
        assert_eq!(reader.get_signal_key("BTCUSDT"), "market:signal:BTCUSDT");
        assert_eq!(reader.get_signal_key("ethusdt"), "market:signal:ETHUSDT");
    }

    #[test]
    fn test_regime_description() {
        assert!(SignalReader::regime_description(&MarketRegime::Trending).contains("trend"));
        assert!(SignalReader::regime_description(&MarketRegime::Ranging).contains("Range"));
        assert!(SignalReader::regime_description(&MarketRegime::Volatile).contains("volatility"));
    }
}
