//! Data models for the Muscle signal engine.
//!
//! This module defines the core data structures used throughout the muscle module,
//! including klines (candlestick data), trading signals, market regimes, and
//! signal output with latency tracking.

use serde::{Deserialize, Serialize};
use std::time::{SystemTime, UNIX_EPOCH};

/// A single candlestick (kline) from Binance.
///
/// Contains OHLCV data plus metadata for latency tracking.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Kline {
    /// Symbol (e.g., "BTCUSDT")
    pub symbol: String,
    /// Close time of the candle in milliseconds since epoch
    pub timestamp_ms: i64,
    /// Open price
    pub open: f64,
    /// High price
    pub high: f64,
    /// Low price
    pub low: f64,
    /// Close price
    pub close: f64,
    /// Trading volume
    pub volume: f64,
    /// Whether this candle is closed (not updating)
    pub is_closed: bool,
    /// Server-side receive timestamp in milliseconds since epoch.
    /// Used for calculating ingestion latency:
    /// `ingestion_latency_ms = current_system_time_ms - received_at_ms`
    pub received_at_ms: i64,
}

impl Kline {
    /// Calculate the typical price (HLC3) for this kline.
    ///
    /// Typical price = (High + Low + Close) / 3
    /// This is commonly used as input for smoothing filters.
    #[inline]
    pub fn typical_price(&self) -> f64 {
        (self.high + self.low + self.close) / 3.0
    }

    /// Calculate the HLC3 typical price with open instead of close (for current candle).
    #[inline]
    pub fn typical_price_with_open(&self) -> f64 {
        (self.high + self.low + self.open) / 3.0
    }

    /// Get the current system time in milliseconds.
    ///
    /// Used for latency calculation.
    pub fn current_time_ms() -> i64 {
        SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("Time went backwards")
            .as_millis() as i64
    }

    /// Calculate the ingestion latency for this kline.
    ///
    /// Returns the time difference between when this kline was received
    /// by our system and the current time, in milliseconds.
    #[inline]
    pub fn ingestion_latency_ms(&self) -> i64 {
        Self::current_time_ms() - self.received_at_ms
    }

    /// Get the price to use for signal generation.
    ///
    /// For closed candles, uses close price.
    /// For open candles, uses typical price with open.
    #[inline]
    pub fn signal_price(&self) -> f64 {
        if self.is_closed {
            self.close
        } else {
            self.typical_price_with_open()
        }
    }
}

/// Market regime classification.
///
/// Determined by ADX and Bollinger Band Width indicators:
/// - **Trending**: ADX > 25 (strong trend)
/// - **Ranging**: ADX < 20 AND BB Width < 5% (weak trend, low volatility)
/// - **Volatile**: BB Width > 10% OR ADX rising rapidly (high volatility)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MarketRegime {
    /// Strong trend market (ADX > 25)
    Trending,
    /// Range-bound market (ADX < 20, low volatility)
    Ranging,
    /// High volatility market (BB Width > 10% or rapid ADX change)
    Volatile,
}

impl std::fmt::Display for MarketRegime {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Trending => write!(f, "TRENDING"),
            Self::Ranging => write!(f, "RANGING"),
            Self::Volatile => write!(f, "VOLATILE"),
        }
    }
}

/// Trading signal direction.
///
/// Generated by strategy analysis and aggregated by the Gatekeeper.
#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(tag = "direction", content = "strength")]
pub enum Signal {
    /// Long (buy) signal with strength 0.0-1.0
    Long { strength: f64 },
    /// Short (sell) signal with strength 0.0-1.0
    Short { strength: f64 },
    /// No position / wait
    Wait,
}

impl Signal {
    /// Convert signal to numeric value for aggregation.
    ///
    /// Long = 1.0, Short = -1.0, Wait = 0.0
    #[inline]
    pub fn to_value(&self) -> f64 {
        match self {
            Self::Long { strength } => *strength,
            Self::Short { strength } => -*strength,
            Self::Wait => 0.0,
        }
    }

    /// Create a Long signal with given strength.
    #[inline]
    pub fn long(strength: f64) -> Self {
        Self::Long {
            strength: strength.clamp(0.0, 1.0),
        }
    }

    /// Create a Short signal with given strength.
    #[inline]
    pub fn short(strength: f64) -> Self {
        Self::Short {
            strength: strength.clamp(0.0, 1.0),
        }
    }

    /// Create a Wait signal.
    #[inline]
    pub fn wait() -> Self {
        Self::Wait
    }
}

impl Default for Signal {
    fn default() -> Self {
        Self::Wait
    }
}

/// Snapshot of key indicator values at signal time.
///
/// Included in Redis output for monitoring and debugging.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct IndicatorSnapshot {
    /// Relative Strength Index (14-period)
    pub rsi: f64,
    /// Upper Bollinger Band value
    pub bb_upper: f64,
    /// Lower Bollinger Band value
    pub bb_lower: f64,
    /// Ultimate Smoother value
    pub us_value: f64,
    /// Average Directional Index
    pub adx: f64,
    /// Bollinger Band Width (normalized)
    pub bb_width: f64,
    /// ATR (Average True Range) value
    pub atr: f64,
    /// MACD line value
    pub macd: f64,
    /// MACD signal line value
    pub macd_signal: f64,
    /// MACD histogram value
    pub macd_histogram: f64,
}

impl Default for IndicatorSnapshot {
    fn default() -> Self {
        Self {
            rsi: 50.0,
            bb_upper: 0.0,
            bb_lower: 0.0,
            us_value: 0.0,
            adx: 0.0,
            bb_width: 0.0,
            atr: 0.0,
            macd: 0.0,
            macd_signal: 0.0,
            macd_histogram: 0.0,
        }
    }
}

/// Complete signal output published to Redis.
///
/// Contains all information needed for downstream consumers
/// to make trading decisions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SignalOutput {
    /// Current price used for signal generation
    pub price: f64,
    /// Timestamp of the signal in milliseconds since epoch
    pub timestamp_ms: i64,
    /// Current market regime
    pub market_regime: MarketRegime,
    /// Aggregated confluence score (-10 to +10)
    /// Positive = bullish bias, Negative = bearish bias
    pub confluence_score: i8,
    /// Snapshot of key indicator values
    pub indicator_snapshot: IndicatorSnapshot,
    /// Final trade advice after aggregation and safety checks
    pub trade_advice: Signal,
    /// Ingestion latency in milliseconds.
    /// Calculated as: `current_system_time_ms - kline_close_time_ms`
    pub ingestion_latency_ms: i64,
    /// Reason if trade_advice was overridden by safety mechanisms.
    /// Common values: "LATENCY_SPIKE", "DATA_GAP", "MARKET_HALT"
    pub override_reason: Option<String>,
}

impl SignalOutput {
    /// Create a new SignalOutput with latency tracking.
    ///
    /// # Arguments
    /// * `price` - Current price
    /// * `timestamp_ms` - Signal timestamp
    /// * `market_regime` - Current market regime
    /// * `confluence_score` - Aggregated score (-10 to +10)
    /// * `indicator_snapshot` - Indicator values
    /// * `trade_advice` - Recommended action
    /// * `kline_timestamp_ms` - Original kline close time for latency calc
    pub fn new(
        price: f64,
        timestamp_ms: i64,
        market_regime: MarketRegime,
        confluence_score: i8,
        indicator_snapshot: IndicatorSnapshot,
        trade_advice: Signal,
        kline_timestamp_ms: i64,
    ) -> Self {
        let ingestion_latency_ms = Kline::current_time_ms() - kline_timestamp_ms;

        Self {
            price,
            timestamp_ms,
            market_regime,
            confluence_score,
            indicator_snapshot,
            trade_advice,
            ingestion_latency_ms,
            override_reason: None,
        }
    }

    /// Apply latency safety check.
    ///
    /// If latency exceeds the threshold, force trade_advice to WAIT
    /// and set override_reason to "LATENCY_SPIKE".
    ///
    /// # Arguments
    /// * `max_allowed_latency_ms` - Maximum acceptable latency in milliseconds
    pub fn apply_latency_safety_check(&mut self, max_allowed_latency_ms: i64) {
        if self.ingestion_latency_ms > max_allowed_latency_ms {
            self.trade_advice = Signal::Wait;
            self.override_reason = Some("LATENCY_SPIKE".to_string());
        }
    }

    /// Check if this signal should be exported (past warm-up period).
    ///
    /// # Arguments
    /// * `candle_index` - Index of the candle in the DataFrame
    /// * `warmup_candles` - Number of warm-up candles to skip
    #[inline]
    pub fn should_export(candle_index: usize, warmup_candles: usize) -> bool {
        candle_index >= warmup_candles
    }
}

/// Binance kline interval enumeration.
///
/// Supported intervals for historical data fetch and WebSocket subscription.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum KlineInterval {
    /// 1 minute
    #[serde(rename = "1m")]
    Minute1,
    /// 3 minutes
    #[serde(rename = "3m")]
    Minute3,
    /// 5 minutes
    #[serde(rename = "5m")]
    Minute5,
    /// 15 minutes
    #[serde(rename = "15m")]
    Minute15,
    /// 30 minutes
    #[serde(rename = "30m")]
    Minute30,
    /// 1 hour
    #[serde(rename = "1h")]
    Hour1,
    /// 2 hours
    #[serde(rename = "2h")]
    Hour2,
    /// 4 hours
    #[serde(rename = "4h")]
    Hour4,
    /// 6 hours
    #[serde(rename = "6h")]
    Hour6,
    /// 8 hours
    #[serde(rename = "8h")]
    Hour8,
    /// 12 hours
    #[serde(rename = "12h")]
    Hour12,
    /// 1 day
    #[serde(rename = "1d")]
    Day1,
    /// 3 days
    #[serde(rename = "3d")]
    Day3,
    /// 1 week
    #[serde(rename = "1w")]
    Week1,
    /// 1 month
    #[serde(rename = "1M")]
    Month1,
}

impl KlineInterval {
    /// Get the interval as a string for API requests.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Minute1 => "1m",
            Self::Minute3 => "3m",
            Self::Minute5 => "5m",
            Self::Minute15 => "15m",
            Self::Minute30 => "30m",
            Self::Hour1 => "1h",
            Self::Hour2 => "2h",
            Self::Hour4 => "4h",
            Self::Hour6 => "6h",
            Self::Hour8 => "8h",
            Self::Hour12 => "12h",
            Self::Day1 => "1d",
            Self::Day3 => "3d",
            Self::Week1 => "1w",
            Self::Month1 => "1M",
        }
    }

    /// Get the interval in milliseconds.
    pub fn as_millis(&self) -> i64 {
        match self {
            Self::Minute1 => 60_000,
            Self::Minute3 => 180_000,
            Self::Minute5 => 300_000,
            Self::Minute15 => 900_000,
            Self::Minute30 => 1_800_000,
            Self::Hour1 => 3_600_000,
            Self::Hour2 => 7_200_000,
            Self::Hour4 => 14_400_000,
            Self::Hour6 => 21_600_000,
            Self::Hour8 => 28_800_000,
            Self::Hour12 => 43_200_000,
            Self::Day1 => 86_400_000,
            Self::Day3 => 259_200_000,
            Self::Week1 => 604_800_000,
            Self::Month1 => 2_592_000_000,
        }
    }

    /// Parse interval from string.
    pub fn from_str(s: &str) -> Option<Self> {
        match s.to_lowercase().as_str() {
            "1m" => Some(Self::Minute1),
            "3m" => Some(Self::Minute3),
            "5m" => Some(Self::Minute5),
            "15m" => Some(Self::Minute15),
            "30m" => Some(Self::Minute30),
            "1h" => Some(Self::Hour1),
            "2h" => Some(Self::Hour2),
            "4h" => Some(Self::Hour4),
            "6h" => Some(Self::Hour6),
            "8h" => Some(Self::Hour8),
            "12h" => Some(Self::Hour12),
            "1d" => Some(Self::Day1),
            "3d" => Some(Self::Day3),
            "1w" => Some(Self::Week1),
            "1M" | "1mo" => Some(Self::Month1),
            _ => None,
        }
    }
}

impl std::fmt::Display for KlineInterval {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_kline_typical_price() {
        let kline = Kline {
            symbol: "BTCUSDT".to_string(),
            timestamp_ms: 1000,
            open: 100.0,
            high: 110.0,
            low: 90.0,
            close: 105.0,
            volume: 1000.0,
            is_closed: true,
            received_at_ms: 1000,
        };

        // Typical price = (110 + 90 + 105) / 3 = 101.666...
        let typical = kline.typical_price();
        assert!((typical - 101.666666).abs() < 0.001);
    }

    #[test]
    fn test_kline_signal_price_closed() {
        let kline = Kline {
            symbol: "BTCUSDT".to_string(),
            timestamp_ms: 1000,
            open: 100.0,
            high: 110.0,
            low: 90.0,
            close: 105.0,
            volume: 1000.0,
            is_closed: true,
            received_at_ms: 1000,
        };

        assert_eq!(kline.signal_price(), 105.0);
    }

    #[test]
    fn test_kline_signal_price_open() {
        let kline = Kline {
            symbol: "BTCUSDT".to_string(),
            timestamp_ms: 1000,
            open: 100.0,
            high: 110.0,
            low: 90.0,
            close: 105.0,
            volume: 1000.0,
            is_closed: false,
            received_at_ms: 1000,
        };

        // Typical price with open = (110 + 90 + 100) / 3 = 100.0
        assert_eq!(kline.signal_price(), 100.0);
    }

    #[test]
    fn test_signal_to_value() {
        assert_eq!(Signal::long(0.8).to_value(), 0.8);
        assert_eq!(Signal::short(0.5).to_value(), -0.5);
        assert_eq!(Signal::wait().to_value(), 0.0);
    }

    #[test]
    fn test_signal_strength_clamping() {
        // Strength should be clamped to 0.0-1.0
        let long = Signal::long(1.5);
        match long {
            Signal::Long { strength } => assert_eq!(strength, 1.0),
            _ => panic!("Expected Long signal"),
        }

        let short = Signal::short(-0.3);
        match short {
            Signal::Short { strength } => assert_eq!(strength, 0.0),
            _ => panic!("Expected Short signal"),
        }
    }

    #[test]
    fn test_market_regime_display() {
        assert_eq!(MarketRegime::Trending.to_string(), "TRENDING");
        assert_eq!(MarketRegime::Ranging.to_string(), "RANGING");
        assert_eq!(MarketRegime::Volatile.to_string(), "VOLATILE");
    }

    #[test]
    fn test_kline_interval_conversion() {
        assert_eq!(KlineInterval::from_str("1m"), Some(KlineInterval::Minute1));
        assert_eq!(KlineInterval::from_str("1H"), Some(KlineInterval::Hour1));
        assert_eq!(KlineInterval::from_str("1d"), Some(KlineInterval::Day1));
        assert_eq!(KlineInterval::from_str("invalid"), None);
    }

    #[test]
    fn test_kline_interval_millis() {
        assert_eq!(KlineInterval::Minute1.as_millis(), 60_000);
        assert_eq!(KlineInterval::Hour1.as_millis(), 3_600_000);
        assert_eq!(KlineInterval::Day1.as_millis(), 86_400_000);
    }

    #[test]
    fn test_signal_output_latency_check() {
        let mut signal = SignalOutput {
            price: 50000.0,
            timestamp_ms: 1000,
            market_regime: MarketRegime::Trending,
            confluence_score: 5,
            indicator_snapshot: IndicatorSnapshot::default(),
            trade_advice: Signal::long(0.8),
            ingestion_latency_ms: 100,
            override_reason: None,
        };

        // Should not trigger at 100ms latency
        signal.apply_latency_safety_check(500);
        assert!(matches!(signal.trade_advice, Signal::Long { .. }));
        assert!(signal.override_reason.is_none());

        // Should trigger at 600ms latency (> 500ms threshold)
        signal.ingestion_latency_ms = 600;
        signal.apply_latency_safety_check(500);
        assert!(matches!(signal.trade_advice, Signal::Wait));
        assert_eq!(signal.override_reason, Some("LATENCY_SPIKE".to_string()));
    }

    #[test]
    fn test_should_export_warmup() {
        // First 100 candles should not be exported (warm-up period)
        for i in 0..100 {
            assert!(!SignalOutput::should_export(i, 100));
        }

        // Candle 100 and beyond should be exported
        assert!(SignalOutput::should_export(100, 100));
        assert!(SignalOutput::should_export(101, 100));
        assert!(SignalOutput::should_export(1000, 100));
    }
}
